version: '3'
services:
  db_test:
    image: mariadb
    hostname: test
    environment:
      MYSQL_ROOT_PASSWORD: asdfghj
      MYSQL_DATABASE: test
      MYSQL_USER: root1
      MYSQL_PASSWORD: asdfghj
    volumes:
      - ./Base de datos/test.sql:/docker-entrypoint-initdb.d/init.sql
      - data2:/var/lib/mysql
    ports:
      - 3312:3306
    networks:
      - red
    stdin_open: true
    tty: true
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./Backend/dockerfile
    ports:
      - 5004:5004
    depends_on:
      - db_test
    
    networks:
      - red
    stdin_open: true
    tty: true
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: dockerfile
    ports:
      - 4003:4003
    
    networks:
      - red
    stdin_open: true
    tty: true
    restart: always

volumes:
  data2:
    external: false

networks:
  red:
    name: red
