name: Run Dev Environments

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Run Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -la
        shell: /usr/bin/bash -e {0}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd Frontend
          npm install
        shell: /usr/bin/bash -e {0}

      - name: Run frontend
        run: |
          cd Frontend
          npm run dev
        shell: /usr/bin/bash -e {0}

  backend:
    name: Run Backend
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -la
        shell: /usr/bin/bash -e {0}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install backend dependencies
        run: |
          cd Backend
          npm install
        shell: /usr/bin/bash -e {0}

      - name: Run backend
        run: |
          cd Backend
          npm run dev
        shell: /usr/bin/bash -e {0}
