name: Run Dev Environments with MariaDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup MariaDB and Run Environments
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -la
        shell: /usr/bin/bash -e {0}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd Frontend
          npm install
        shell: /usr/bin/bash -e {0}

      - name: Run frontend
        run: |
          cd Frontend
          npm run dev
        shell: /usr/bin/bash -e {0}

      - name: Install backend dependencies
        run: |
          cd Backend
          npm install
        shell: /usr/bin/bash -e {0}

      - name: Run backend
        run: |
          cd Backend
          npm run dev
        shell: /usr/bin/bash -e {0}
