name: CI Pipeline for Dockerized Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: C:\DockerCache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Compose
        run: docker-compose up -d --build

      - name: Wait for MySQL to be ready
        shell: bash
        run: |
          echo "Waiting for MySQL to be ready..."
          while ! docker-compose exec -T db_test mysql --host=db_test --user=root1 --password=asdfghj -e "SELECT 1"; do
            sleep 1
          done

      - name: Wait for Backend to be ready
        shell: bash
        run: |
          echo "Waiting for Backend to be ready..."
          while ! docker-compose exec -T backend netstat -an | grep 5004 | grep LISTEN; do
            sleep 1
          done

      - name: Wait for Frontend to be ready
        shell: bash
        run: |
          echo "Waiting for Frontend to be ready..."
          while ! docker-compose exec -T frontend netstat -an | grep 4003 | grep LISTEN; do
            sleep 1
          done

  #    - name: Run Backend Tests
   #     run: docker-compose exec -T backend npm test

    #  - name: Run Frontend Tests
     #   run: docker-compose exec -T frontend npm test

      - name: Tear down Docker Compose
        run: docker-compose down
